# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
image: ruby:latest

# Cache gems in between builds
cache:
  paths:
  - .bundle

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
- ruby -v                                   # Print out ruby version for debugging
- gem install bundler --no-ri --no-rdoc     # Bundler is not installed with the image
- bundle install -j $(nproc) --path .bundle # Install dependencies into ./.bundle

rake:
  script:
  - rake
