#!/usr/bin/env ruby
require 'bundler/setup'
require 'xommelier'
require 'nokogiri'
require 'ripl'
require 'pp'

SPEC_ROOT = File.expand_path('..', __FILE__)

Dir[File.join(SPEC_ROOT, 'spec/support/**/*.rb')].each {|f| require f}

Ripl.start
