require 'rspec/xommelier/active_model'
require 'rspec/xommelier/hash_with_references'
require 'rspec/xommelier/xml/schema'
require 'rspec/xommelier/xml/schema/type'
require 'rspec/xommelier/xml/schema/simple_type'
require 'rspec/xommelier/xml/schema/complex_type'
require 'rspec/xommelier/xml/schema/explicit_group'
