# This file is automatically generated
# Please do not edit it

require 'xommelier/xml/schema'

module Xommelier
  # DCMES 1.1 XML Schema
  # XML Schema for http://purl.org/dc/elements/1.1/ namespace
  # Created 2008-02-11
  # Created by 
  # Tim Cole (t-cole3@uiuc.edu)
  # Tom Habing (thabing@uiuc.edu)
  # Jane Hunter (jane@dstc.edu.au)
  # Pete Johnston (p.johnston@ukoln.ac.uk),
  # Carl Lagoze (lagoze@cs.cornell.edu)
  # This schema declares XML elements for the 15 DC elements from the
  # http://purl.org/dc/elements/1.1/ namespace.
  # It defines a complexType SimpleLiteral which permits mixed content 
  # and makes the xml:lang attribute available. It disallows child elements by
  # use of minOcccurs/maxOccurs.
  # However, this complexType does permit the derivation of other complexTypes
  # which would permit child elements.
  # All elements are declared as substitutable for the abstract element any, 
  # which means that the default type for all elements is dc:SimpleLiteral.
  schema :xmlns, xmlns: {xs: "http://www.w3.org/2001/XMLSchema", xmlns: "http://purl.org/dc/elements/1.1/"}, elementFormDefault: "qualified", attributeFormDefault: "unqualified" do
    namespace "http://purl.org/dc/elements/1.1/", as: :xmlns
    import "http://www.w3.org/XML/1998/namespace", schemaLocation: "http://www.w3.org/2001/03/xml.xsd"
    # This is the default type for all of the DC elements.
    # It permits text content only with optional
    # xml:lang attribute.
    # Text is allowed because mixed="true", but sub-elements
    # are disallowed because minOccurs="0" and maxOccurs="0" 
    # are on the xs:any tag.
    # This complexType allows for restriction or extension permitting
    # child elements.
    complex_type :SimpleLiteral do
      complex_content base: ns.xs.anyType, ref: ns.xml.lang, required: false, mixed: "true"
    end
    element :any, type: :SimpleLiteral, abstract: "true"
    element :title, substitutionGroup: "any"
    element :creator, substitutionGroup: "any"
    element :subject, substitutionGroup: "any"
    element :description, substitutionGroup: "any"
    element :publisher, substitutionGroup: "any"
    element :contributor, substitutionGroup: "any"
    element :date, substitutionGroup: "any"
    element :type, substitutionGroup: "any"
    element :format, substitutionGroup: "any"
    element :identifier, substitutionGroup: "any"
    element :source, substitutionGroup: "any"
    element :language, substitutionGroup: "any"
    element :relation, substitutionGroup: "any"
    element :coverage, substitutionGroup: "any"
    element :rights, substitutionGroup: "any"
    # This group is included as a convenience for schema authors
    # who need to refer to all the elements in the 
    # http://purl.org/dc/elements/1.1/ namespace.
    group :elementsGroup do
      sequence do
        choice min: 0, max: :unbounded do
          element ref: :any
        end
      end
    end
    # This complexType is included as a convenience for schema authors who need to define a root
    # or container element for all of the DC elements.
    complex_type :elementContainer do
      choice do
        group ref: :elementsGroup
      end
    end
  end
end
