# This file is automatically generated
# Please do not edit it

require 'xommelier/xml/schema'

module Xommelier
  # DCMI Type Vocabulary XML Schema
  # XML Schema for http://purl.org/dc/dcmitype/ namespace
  # Created 2008-02-11
  # Created by 
  # Tim Cole (t-cole3@uiuc.edu)
  # Tom Habing (thabing@uiuc.edu)
  # Jane Hunter (jane@dstc.edu.au)
  # Pete Johnston (p.johnston@ukoln.ac.uk),
  # Carl Lagoze (lagoze@cs.cornell.edu)
  # This schema defines a simpleType which enumerates
  # the allowable values for the DCMI Type Vocabulary.
  schema :xmlns, xmlns: {xs: "http://www.w3.org/2001/XMLSchema", xmlns: "http://purl.org/dc/dcmitype/"}, elementFormDefault: "qualified", attributeFormDefault: "unqualified" do
    namespace "http://purl.org/dc/dcmitype/", as: :xmlns
    simple_type :DCMIType do
      union do
        simple_type base: ns.xs.Name, enumeration: ["Collection", "Dataset", "Event", "Image", "MovingImage", "StillImage", "InteractiveResource", "Service", "Software", "Sound", "Text", "PhysicalObject"]
      end
    end
  end
end
