# This file is automatically generated
# Please do not edit it

require 'xommelier/xml/schema'

module Xommelier
  schema :t, xmlns: {xmlns: "http://www.w3.org/2001/XMLSchema", t: "http://www.w3.org/namespace/"} do
    namespace "http://www.w3.org/namespace/", as: :t
    element :plist do
      complex_type do
        choice do
          element ref: :array
          element ref: :data
          element ref: :date
          element ref: :dict
          element ref: :real
          element ref: :integer
          element ref: :string
          element ref: :true
          element ref: :false
        end
        attribute :version, type: :string, required: true
      end
    end
    element :array do
      complex_type do
        sequence min: 0, max: :unbounded do
          choice do
            element ref: :array
            element ref: :data
            element ref: :date
            element ref: :dict
            element ref: :real
            element ref: :integer
            element ref: :string
            element ref: :true
            element ref: :false
          end
        end
      end
    end
    element :dict do
      complex_type do
        sequence min: 0, max: :unbounded do
          element ref: :key
          choice do
            element ref: :array
            element ref: :data
            element ref: :date
            element ref: :dict
            element ref: :real
            element ref: :integer
            element ref: :string
            element ref: :true
            element ref: :false
          end
        end
      end
    end
    element :key, type: :string
    element :string, type: :string
    element :data, type: :base64Binary
    element :date, type: :dateTime
    element :true
    element :false
    element :real, type: :decimal
    element :integer, type: :integer
  end
end
