# This file is automatically generated
# Please do not edit it

require 'xommelier/xml/schema'

module Xommelier
  # Version 1.1.0 fixed double quotes in default values. Adjusted image height and width to use a restricted decimal rather than the nonNegativeInteger.
  schema :xmlns, xmlns: {xmlns: "http://blogs.law.harvard.edu/RSS20.xsd", xs: "http://www.w3.org/2001/XMLSchema"}, version: "1.1.0" do
    namespace "http://blogs.law.harvard.edu/RSS20.xsd", as: :xmlns
    element :rss do
      complex_type do
        sequence do
          element :channel, type: :channel
        end
      end
    end
    complex_type :channel do
      sequence do
        # The name of the channel. It's how people refer to your service. If you have an HTML website that contains the same information as your RSS file, the title of your channel should be the same as the title of your website.
        element :title, min: 1, max: 1
        # The URL to the HTML website corresponding to the channel.
        element :link, min: 1, max: 1
        # Phrase or sentence describing the channel.
        element :description, min: 1, max: 1
        # The language the channel is written in. This allows aggregators to group all Italian language sites, for example, on a single page. A list of allowable values for this element, as provided by Netscape, is http://blogs.law.harvard.edu/tech/stories/storyReader$15 here. You may also use http://www.w3.org/TR/REC-html40/struct/dirlang.html#langcodes values defined by the W3C.
        element :language, min: 0, max: 1, default: "en-us" do
          simple_type base: ns.xs.string
        end
        # Copyright notice for content in the channel.
        element :copyright
        # Email address for person responsible for editorial content.
        element :managingEditor
        # Email address for person responsible for technical issues relating to channel.
        element :webMaster
        # The publication date for the content in the channel. For example, the New York Times publishes on a daily basis, the publication date flips once every 24 hours. That's when the pubDate of the channel changes. All date-times in RSS conform to the Date and Time Specification of http://asg.web.cmu.edu/rf/rfc822.html RFC 822, with the exception that the year may be expressed with two characters or four characters (four preferred).
        element :pubDate
        # The last time the content of the channel changed.
        element :lastBuildDate
        # Specify one or more categories that the channel belongs to. Follows the same rules as the item-level http://blogs.law.harvard.edu/tech/rss#ltcategorygtSubelementOfLtitemgt" category element. More http://blogs.law.harvard.edu/tech/rss#syndic8 info.
        element :category
        # A string indicating the program used to generate the channel.
        element :generator
        # A URL that points to the documentation for the format used in the RSS file. It's probably a pointer to this page. It's for people who might stumble across an RSS file on a Web server 25 years from now and wonder what it is.
        element :docs, default: "http://blogs.law.harvard.edu/tech/rss" do
          simple_type base: ns.xs.string
        end
        element :cloud do
          # Allows processes to register with a cloud to be notified of updates to the channel, implementing a lightweight publish-subscribe protocol for RSS feeds. More info http://blogs.law.harvard.edu/tech/rss#ltcloudgtSubelementOfLtchannelgt here.
          complex_type do
            attribute :domain
            attribute :port
            attribute :path
            attribute :registerProcedure
            attribute :protocol, simple_type: {base: ns.xs.string, enumeration: ["xml-rpc", "soap"]}
          end
        end
        # ttl stands for time to live. It's a number of minutes that indicates how long a channel can be cached before refreshing from the source. 
        # More info http://blogs.law.harvard.edu/tech/rss#ltttlgtSubelementOfLtchannelgt here.
        element :ttl
        # Specifies a GIF, JPEG or PNG image that can be displayed with the channel. More info http://blogs.law.harvard.edu/tech/rss#ltimagegtSubelementOfLtchannelgt here.
        element :image do
          complex_type do
            sequence do
              # The URL of a GIF, JPEG or PNG image that represents the channel.
              element :url, min: 1, max: 1
              # Describes the image, it's used in the ALT attribute of the HTML img tag when the channel is rendered in HTML.
              element :title, min: 1, max: 1
              # The URL of the site, when the channel is rendered, the image is a link to the site. (Note, in practice the image title and link should have the same value as the channel's title and link.)
              element :link, min: 1, max: 1
              element :width, default: "88" do
                simple_type base: ns.xs.decimal, gte: 144, lte: 0, fraction_digits: {value: 0}
              end
              element :height, default: "31" do
                simple_type base: ns.xs.decimal, gte: 400, lte: 0, fraction_digits: {value: 0}
              end
              # Contains text that is included in the TITLE attribute of the link formed around the image in the HTML rendering.
              element :description
            end
          end
        end
        # The http://www.w3.org/PICS/ PICS rating for the channel.
        element :rating
        # Specifies a text input box that can be displayed with the channel. More info http://blogs.law.harvard.edu/tech/rss#lttextinputgtSubelementOfLtchannelgt here.
        # The purpose of the textInput element is something of a mystery. You can use it to specify a search engine box. Or to allow a reader to provide feedback. Most aggregators ignore it.
        element :textInput do
          complex_type do
            sequence do
              # The label of the Submit button in the text input area.
              element :title
              # Explains the text input area.
              element :description
              # The name of the text object in the text input area.
              element :name
              # The URL of the CGI script that processes text input requests.
              element :link
            end
          end
        end
        # A hint for aggregators telling them which hours they can skip. 
        # More info http://blogs.law.harvard.edu/tech/skipHoursDays#skiphours here.
        element :skipHours
        # A hint for aggregators telling them which days they can skip. 
        # More info http://blogs.law.harvard.edu/tech/skipHoursDays#skipdays here.
        element :skipDays
        element :item, type: :item, min: 0, max: :unbounded
      end
      attribute :version, default: "2.0"
    end
    # A channel may contain any number of items. An item may represent a "story" -- much like a story in a newspaper or magazine; if so its description is a synopsis of the story, and the link points to the full story. An item may also be complete in itself, if so, the description contains the text 
    # (entity-encoded HTML is allowed), and the link and title may be omitted. All elements of an item are optional, however at least one of title or description must be present.
    complex_type :item do
      sequence do
        element :title
        # The URL of the item.
        element :link
        # The item synopsis.
        element :description
        # It's the email address of the author of the item. For newspapers and magazines syndicating via RSS, the author is the person who wrote the article that the item describes. For collaborative weblogs, the author of the item might be different from the managing editor or webmaster. For a weblog authored by a single individual it would make sense to omit the author element.
        element :author, min: 0, max: 1
        element :category, min: 0, max: :unbounded do
          complex_type do
            # The value of the element is a forward-slash-separated string that identifies a hierarchic location in the indicated taxonomy. Processors may establish conventions for the interpretation of categories.
            attribute :domain, required: false
          end
        end
        # If present, it is the url of the comments page for the item.
        element :comments, min: 0, max: 1
        # Describes a media object that is attached to the item.
        element :enclosure, min: 0, max: 1 do
          complex_type do
            # Where the enclosure is located
            attribute :url, required: true
            # How big it is in bytes.
            attribute :length, required: true
            # What its type is, a standard MIME type.
            attribute :type, required: true
          end
        end
        # A string that uniquely identifies the item. There are no rules for the syntax of a guid. Aggregators must view them as a string. It's up to the source of the feed to establish the uniqueness of the string.
        element :guid, min: 0, max: 1
        # Indicates when the item was published.
        element :pubDate, min: 0, max: 1
        # The RSS channel that the item came from. The purpose of this element is to propagate credit for links, to publicize the sources of news items. It can be used in the Post command of an aggregator. It should be generated automatically when forwarding an item from an aggregator to a weblog authoring tool.
        element :source, min: 0, max: 1 do
          complex_type do
            # links to the XMLization of the source
            attribute :url, required: true
          end
        end
      end
    end
  end
end
