# This file is automatically generated
# Please do not edit it

require 'xommelier/xml/schema'

module Xommelier
  # Part 1 version: Id: structures.xsd,v 1.2 2004/01/15 11:34:25 ht Exp
  # Part 2 version: Id: datatypes.xsd,v 1.3 2004/01/23 18:11:13 ht Exp
  schema :xs, xmlns: {xs: "http://www.w3.org/2001/XMLSchema", hfp: "http://www.w3.org/2001/XMLSchema-hasFacetAndProperty"}, blockDefault: "#all", elementFormDefault: "qualified", version: "1.0", lang: "EN" do
    namespace "http://www.w3.org/2001/XMLSchema", as: :xs
    # The schema corresponding to this document is normative,
    # with respect to the syntactic constraints it expresses in the
    # XML Schema language.  The documentation (within <documentation> elements)
    # below, is not normative, but rather highlights important aspects of
    # the W3C Recommendation of which this is a part
    # The simpleType element and all of its members are defined
    # towards the end of this schema document
    # Get access to the xml: attribute groups for xml:lang
    # as declared on 'schema' and 'documentation' below
    import "http://www.w3.org/XML/1998/namespace", schemaLocation: "http://www.w3.org/2001/xml.xsd"
    # This type is extended by almost all schema types
    # to allow attributes from other namespaces to be
    # added to user schemas.
    complex_type :openAttrs do
      complex_content base: ns.xs.anyType, ns: "##other", process_contents: :lax
    end
    # This type is extended by all types which allow annotation
    # other than <schema> itself
    complex_type :annotated do
      complex_content base: ns.xs.openAttrs do
        sequence do
          element ref: :annotation, min: 0
        end
        attribute :id, type: :ID
      end
    end
    # This group is for the
    # elements which occur freely at the top level of schemas.
    # All of their types are based on the "annotated" type by extension.
    group :schemaTop do
      choice do
        group ref: :redefinable
        element ref: :element
        element ref: :attribute
        element ref: :notation
      end
    end
    # This group is for the
    # elements which can self-redefine (see <redefine> below).
    group :redefinable do
      choice do
        element ref: :simpleType
        element ref: :complexType
        element ref: :group
        element ref: :attributeGroup
      end
    end
    # A utility type, not for public use
    simple_type :formChoice, base: ns.xs.NMTOKEN, enumeration: ["qualified", "unqualified"]
    # A utility type, not for public use
    simple_type :reducedDerivationControl, base: ns.xs.derivationControl, enumeration: ["extension", "restriction"]
    # A utility type, not for public use
    simple_type :derivationSet do
      union do
        simple_type base: ns.xs.token, enumeration: ["#all"]
        simple_type do
          list item_type: :reducedDerivationControl
        end
      end
    end
    # A utility type, not for public use
    simple_type :typeDerivationControl, base: ns.xs.derivationControl, enumeration: ["extension", "restriction", "list", "union"]
    # A utility type, not for public use
    simple_type :fullDerivationSet do
      union do
        simple_type base: ns.xs.token, enumeration: ["#all"]
        simple_type do
          list item_type: :typeDerivationControl
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-schema}
    element :schema, id: :schema do
      complex_type do
        complex_content base: ns.xs.openAttrs do
          sequence do
            choice min: 0, max: :unbounded do
              element ref: :include
              element ref: :import
              element ref: :redefine
              element ref: :annotation
            end
            sequence min: 0, max: :unbounded do
              group ref: :schemaTop
              element ref: :annotation, min: 0, max: :unbounded
            end
          end
          attribute :targetNamespace, type: :anyURI
          attribute :version, type: :token
          attribute :finalDefault, type: :fullDerivationSet, required: false, default: ""
          attribute :blockDefault, type: :blockSet, required: false, default: ""
          attribute :attributeFormDefault, type: :formChoice, required: false, default: "unqualified"
          attribute :elementFormDefault, type: :formChoice, required: false, default: "unqualified"
          attribute :id, type: :ID
          attribute ref: ns.xml.lang
        end
      end
      key :element, selector: "xs:element", field: "@name"
      key :attribute, selector: "xs:attribute", field: "@name"
      key :type, selector: "xs:complexType|xs:simpleType", field: "@name"
      key :group, selector: "xs:group", field: "@name"
      key :attributeGroup, selector: "xs:attributeGroup", field: "@name"
      key :notation, selector: "xs:notation", field: "@name"
      key :identityConstraint, selector: ".//xs:key|.//xs:unique|.//xs:keyref", field: "@name"
    end
    # for maxOccurs
    simple_type :allNNI do
      union member_types: [:nonNegativeInteger] do
        simple_type base: ns.xs.NMTOKEN, enumeration: ["unbounded"]
      end
    end
    # for all particles
    attribute_group :occurs, name: "occurs" do
      attribute :minOccurs, type: :nonNegativeInteger, required: false, default: "1"
      attribute :maxOccurs, type: :allNNI, required: false, default: "1"
    end
    # for element, group and attributeGroup,
    # which both define and reference
    attribute_group :defRef, name: "defRef" do
      attribute :name, type: :NCName
      attribute :ref, type: :QName
    end
    # 'complexType' uses this
    group :typeDefParticle do
      choice do
        element :group, type: :groupRef
        element ref: :all
        element ref: :choice
        element ref: :sequence
      end
    end
    group :nestedParticle do
      choice do
        element :element, type: :localElement
        element :group, type: :groupRef
        element ref: :choice
        element ref: :sequence
        element ref: :any
      end
    end
    group :particle do
      choice do
        element :element, type: :localElement
        element :group, type: :groupRef
        element ref: :all
        element ref: :choice
        element ref: :sequence
        element ref: :any
      end
    end
    complex_type :attribute do
      complex_content base: ns.xs.annotated do
        sequence do
          element :simpleType, type: :localSimpleType, min: 0
        end
        attribute_group ref: :defRef
        attribute :type, type: :QName
        attribute :use, simple_type: {base: ns.xs.NMTOKEN, enumeration: ["prohibited", "optional", "required"]}, required: false, default: "optional"
        attribute :default, type: :string
        attribute :fixed, type: :string
        attribute :form, type: :formChoice
      end
    end
    complex_type :topLevelAttribute do
      complex_content base: ns.xs.attribute, required: true, type: ns.xs.NCName, ns: "##other", process_contents: :lax
    end
    group :attrDecls do
      sequence do
        choice min: 0, max: :unbounded do
          element :attribute, type: :attribute
          element :attributeGroup, type: :attributeGroupRef
        end
        element ref: :anyAttribute, min: 0
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-anyAttribute}
    element :anyAttribute, id: :anyAttribute, type: :wildcard
    group :complexTypeModel do
      choice do
        element ref: :simpleContent
        element ref: :complexContent
        # This branch is short for
        # <complexContent>
        # <restriction base="xs:anyType">
        # ...
        # </restriction>
        # </complexContent>
        sequence do
          group ref: :typeDefParticle, min: 0
          group ref: :attrDecls
        end
      end
    end
    complex_type :complexType, abstract: true do
      complex_content base: ns.xs.annotated do
        group ref: :complexTypeModel
        # Will be restricted to required or forbidden
        attribute :name, type: :NCName
        # Not allowed if simpleContent child is chosen.
        # May be overriden by setting on complexContent child.
        attribute :mixed, type: :boolean, required: false, default: "false"
        attribute :abstract, type: :boolean, required: false, default: "false"
        attribute :final, type: :derivationSet
        attribute :block, type: :derivationSet
      end
    end
    complex_type :topLevelComplexType do
      complex_content base: ns.xs.complexType, type: ns.xs.NCName, required: true, ns: "##other", process_contents: :lax
    end
    complex_type :localComplexType do
      complex_content base: ns.xs.complexType, required: "prohibited", ns: "##other", process_contents: :lax
    end
    complex_type :restrictionType do
      complex_content base: ns.xs.annotated do
        sequence do
          choice min: 0 do
            group ref: :typeDefParticle
            group ref: :simpleRestrictionModel
          end
          group ref: :attrDecls
        end
        attribute :base, type: :QName, required: true
      end
    end
    complex_type :complexRestrictionType do
      complex_content base: ns.xs.restrictionType, ns: "##other", process_contents: :lax
    end
    complex_type :extensionType do
      complex_content base: ns.xs.annotated do
        sequence do
          group ref: :typeDefParticle, min: 0
          group ref: :attrDecls
        end
        attribute :base, type: :QName, required: true
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-complexContent}
    element :complexContent, id: :complexContent do
      complex_type do
        complex_content base: ns.xs.annotated do
          choice do
            element :restriction, type: :complexRestrictionType
            element :extension, type: :extensionType
          end
          # Overrides any setting on complexType parent.
          attribute :mixed, type: :boolean
        end
      end
    end
    complex_type :simpleRestrictionType do
      complex_content base: ns.xs.restrictionType, ns: "##other", process_contents: :lax
    end
    complex_type :simpleExtensionType do
      complex_content base: ns.xs.extensionType, ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-simpleContent}
    element :simpleContent, id: :simpleContent do
      complex_type do
        complex_content base: ns.xs.annotated do
          choice do
            element :restriction, type: :simpleRestrictionType
            element :extension, type: :simpleExtensionType
          end
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-complexType}
    element :complexType, id: :complexType, type: :topLevelComplexType
    # A utility type, not for public use
    simple_type :blockSet do
      union do
        simple_type base: ns.xs.token, enumeration: ["#all"]
        simple_type do
          list do
            simple_type base: ns.xs.derivationControl, enumeration: ["extension", "restriction", "substitution"]
          end
        end
      end
    end
    # The element element can be used either
    # at the top level to define an element-type binding globally,
    # or within a content model to either reference a globally-defined
    # element or type or declare an element-type binding locally.
    # The ref form is not allowed at the top level.
    complex_type :element, abstract: true do
      complex_content base: ns.xs.annotated do
        sequence do
          choice min: 0 do
            element :simpleType, type: :localSimpleType
            element :complexType, type: :localComplexType
          end
          group ref: :identityConstraint, min: 0, max: :unbounded
        end
        attribute_group ref: :defRef
        attribute :type, type: :QName
        attribute :substitutionGroup, type: :QName
        attribute_group ref: :occurs
        attribute :default, type: :string
        attribute :fixed, type: :string
        attribute :nillable, type: :boolean, required: false, default: "false"
        attribute :abstract, type: :boolean, required: false, default: "false"
        attribute :final, type: :derivationSet
        attribute :block, type: :blockSet
        attribute :form, type: :formChoice
      end
    end
    complex_type :topLevelElement do
      complex_content base: ns.xs.element, required: true, type: ns.xs.NCName, ns: "##other", process_contents: :lax
    end
    complex_type :localElement do
      complex_content base: ns.xs.element, required: "prohibited", ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-element}
    element :element, id: :element, type: :topLevelElement
    # group type for explicit groups, named top-level groups and
    # group references
    complex_type :group, abstract: true do
      complex_content base: ns.xs.annotated do
        group ref: :particle, min: 0, max: :unbounded
        attribute_group ref: :defRef
        attribute_group ref: :occurs
      end
    end
    complex_type :realGroup do
      complex_content base: ns.xs.group, ns: "##other", process_contents: :lax
    end
    complex_type :namedGroup do
      complex_content base: ns.xs.realGroup, type: ns.xs.NCName, required: "prohibited", ns: "##other", process_contents: :lax
    end
    complex_type :groupRef do
      complex_content base: ns.xs.realGroup, type: ns.xs.QName, required: "prohibited", ns: "##other", process_contents: :lax
    end
    # group type for the three kinds of group
    complex_type :explicitGroup do
      complex_content base: ns.xs.group, type: ns.xs.QName, required: "prohibited", ns: "##other", process_contents: :lax
    end
    complex_type :simpleExplicitGroup do
      complex_content base: ns.xs.explicitGroup, required: "prohibited", ns: "##other", process_contents: :lax
    end
    group :allModel do
      sequence do
        element ref: :annotation, min: 0
        # This choice with min/max is here to
        # avoid a pblm with the Elt:All/Choice/Seq
        # Particle derivation constraint
        choice min: 0, max: :unbounded do
          element :element, type: :narrowMaxMin
        end
      end
    end
    # restricted max/min
    complex_type :narrowMaxMin do
      complex_content base: ns.xs.localElement, simple_type: {base: ns.xs.allNNI, enumeration: ["0", "1"]}, required: false, default: "1", ns: "##other", process_contents: :lax
    end
    # Only elements allowed inside
    complex_type :all do
      complex_content base: ns.xs.explicitGroup, ref: ns.xs.allModel, simple_type: {base: ns.xs.allNNI, enumeration: ["1"]}, required: false, default: "1", ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-all}
    element :all, id: :all, type: :all
    # {http://www.w3.org/TR/xmlschema-1/#element-choice}
    element :choice, id: :choice, type: :explicitGroup
    # {http://www.w3.org/TR/xmlschema-1/#element-sequence}
    element :sequence, id: :sequence, type: :explicitGroup
    # {http://www.w3.org/TR/xmlschema-1/#element-group}
    element :group, id: :group, type: :namedGroup
    complex_type :wildcard do
      complex_content base: ns.xs.annotated do
        attribute :namespace, type: :namespaceList, required: false, default: "##any"
        attribute :processContents, simple_type: {base: ns.xs.NMTOKEN, enumeration: ["skip", "lax", "strict"]}, required: false, default: "strict"
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-any}
    element :any, id: :any do
      complex_type do
        complex_content base: ns.xs.wildcard do
          attribute_group ref: :occurs
        end
      end
    end
    # simple type for the value of the 'namespace' attr of
    # 'any' and 'anyAttribute'
    # Value is
    # ##any      - - any non-conflicting WFXML/attribute at all
    # ##other    - - any non-conflicting WFXML/attribute from
    # namespace other than targetNS
    # ##local    - - any unqualified non-conflicting WFXML/attribute
    # one or     - - any non-conflicting WFXML/attribute from
    # more URI        the listed namespaces
    # references
    # (space separated)
    # ##targetNamespace or ##local may appear in the above list, to
    # refer to the targetNamespace of the enclosing
    # schema or an absent targetNamespace respectively
    # A utility type, not for public use
    simple_type :namespaceList do
      union do
        simple_type base: ns.xs.token, enumeration: ["##any", "##other"]
        simple_type do
          list do
            simple_type do
              union member_types: [:anyURI] do
                simple_type base: ns.xs.token, enumeration: ["##targetNamespace", "##local"]
              end
            end
          end
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-attribute}
    element :attribute, id: :attribute, type: :topLevelAttribute
    complex_type :attributeGroup, abstract: true do
      complex_content base: ns.xs.annotated do
        group ref: :attrDecls
        attribute_group ref: :defRef
      end
    end
    complex_type :namedAttributeGroup do
      complex_content base: ns.xs.attributeGroup, type: ns.xs.NCName, required: "prohibited", ns: "##other", process_contents: :lax
    end
    complex_type :attributeGroupRef do
      complex_content base: ns.xs.attributeGroup, type: ns.xs.QName, required: "prohibited", ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-attributeGroup}
    element :attributeGroup, id: :attributeGroup, type: :namedAttributeGroup
    # {http://www.w3.org/TR/xmlschema-1/#element-include}
    element :include, id: :include do
      complex_type do
        complex_content base: ns.xs.annotated do
          attribute :schemaLocation, type: :anyURI, required: true
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-redefine}
    element :redefine, id: :redefine do
      complex_type do
        complex_content base: ns.xs.openAttrs do
          choice min: 0, max: :unbounded do
            element ref: :annotation
            group ref: :redefinable
          end
          attribute :schemaLocation, type: :anyURI, required: true
          attribute :id, type: :ID
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-import}
    element :import, id: :import do
      complex_type do
        complex_content base: ns.xs.annotated do
          attribute :namespace, type: :anyURI
          attribute :schemaLocation, type: :anyURI
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-selector}
    element :selector, id: :selector do
      complex_type do
        complex_content base: ns.xs.annotated do
          attribute :xpath, simple_type: {base: ns.xs.token, pattern: /(\.\/\/)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(\/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*(\|(\.\/\/)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(\/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*)*/}, required: true
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-field}
    element :field, id: :field do
      complex_type do
        complex_content base: ns.xs.annotated do
          attribute :xpath, simple_type: {base: ns.xs.token, pattern: /(\.\/\/)?((((child::)?((\i\c*:)?(\i\c*|\*)))|\.)\/)*((((child::)?((\i\c*:)?(\i\c*|\*)))|\.)|((attribute::|@)((\i\c*:)?(\i\c*|\*))))(\|(\.\/\/)?((((child::)?((\i\c*:)?(\i\c*|\*)))|\.)\/)*((((child::)?((\i\c*:)?(\i\c*|\*)))|\.)|((attribute::|@)((\i\c*:)?(\i\c*|\*)))))*/}, required: true
        end
      end
    end
    complex_type :keybase do
      complex_content base: ns.xs.annotated do
        sequence do
          element ref: :selector
          element ref: :field, min: 1, max: :unbounded
        end
        attribute :name, type: :NCName, required: true
      end
    end
    # The three kinds of identity constraints, all with
    # type of or derived from 'keybase'.
    group :identityConstraint do
      choice do
        element ref: :unique
        element ref: :key
        element ref: :keyref
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-unique}
    element :unique, id: :unique, type: :keybase
    # {http://www.w3.org/TR/xmlschema-1/#element-key}
    element :key, id: :key, type: :keybase
    # {http://www.w3.org/TR/xmlschema-1/#element-keyref}
    element :keyref, id: :keyref do
      complex_type do
        complex_content base: ns.xs.keybase do
          attribute :refer, type: :QName, required: true
        end
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-notation}
    element :notation, id: :notation do
      complex_type do
        complex_content base: ns.xs.annotated do
          attribute :name, type: :NCName, required: true
          attribute :public, type: :public
          attribute :system, type: :anyURI
        end
      end
    end
    # A utility type, not for public use
    simple_type :public, base: ns.xs.token
    # {http://www.w3.org/TR/xmlschema-1/#element-appinfo}
    element :appinfo, id: :appinfo do
      complex_type mixed: true do
        sequence min: 0, max: :unbounded do
          any process_contents: :lax
        end
        attribute :source, type: :anyURI
        any_attribute ns: "##other", process_contents: :lax
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-documentation}
    element :documentation, id: :documentation do
      complex_type mixed: true do
        sequence min: 0, max: :unbounded do
          any process_contents: :lax
        end
        attribute :source, type: :anyURI
        attribute ref: ns.xml.lang
        any_attribute ns: "##other", process_contents: :lax
      end
    end
    # {http://www.w3.org/TR/xmlschema-1/#element-annotation}
    element :annotation, id: :annotation do
      complex_type do
        complex_content base: ns.xs.openAttrs do
          choice min: 0, max: :unbounded do
            element ref: :appinfo
            element ref: :documentation
          end
          attribute :id, type: :ID
        end
      end
    end
    # notations for use within XML Schema schemas
  # <xs:notation name="XMLSchemaStructures" public="structures" system="http://www.w3.org/2000/08/XMLSchema.xsd"/>
  # <xs:notation name="XML" public="REC-xml-19980210" system="http://www.w3.org/TR/1998/REC-xml-19980210"/>
    # Not the real urType, but as close an approximation as we can
    # get in the XML representation
    complex_type :anyType, mixed: true do
      sequence do
        any process_contents: :lax, min: 0, max: :unbounded
      end
      any_attribute process_contents: :lax
    end
    # First the built-in primitive datatypes.  These definitions are for
    # information only, the real built-in definitions are magic.
    # {http://www.w3.org/TR/xmlschema-2/#string}
    simple_type :string, base: ns.xs.anySimpleType, white_space: {value: "preserve", id: :"string.preserve"}
    # {http://www.w3.org/TR/xmlschema-2/#boolean}
    simple_type :boolean, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"boolean.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#float}
    simple_type :float, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"float.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#double}
    simple_type :double, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"double.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#decimal}
    simple_type :decimal, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"decimal.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#duration}
    simple_type :duration, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"duration.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#dateTime}
    simple_type :dateTime, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"dateTime.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#time}
    simple_type :time, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"time.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#date}
    simple_type :date, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"date.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#gYearMonth}
    simple_type :gYearMonth, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"gYearMonth.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#gYear}
    simple_type :gYear, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"gYear.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#gMonthDay}
    simple_type :gMonthDay, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"gMonthDay.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#gDay}
    simple_type :gDay, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"gDay.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#gMonth}
    simple_type :gMonth, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"gMonth.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#binary}
    simple_type :hexBinary, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"hexBinary.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#base64Binary}
    simple_type :base64Binary, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"base64Binary.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#anyURI}
    simple_type :anyURI, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"anyURI.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#QName}
    simple_type :QName, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"QName.whiteSpace", fixed: true}
    # {http://www.w3.org/TR/xmlschema-2/#NOTATION}
    simple_type :NOTATION, base: ns.xs.anySimpleType, white_space: {value: "collapse", id: :"NOTATION.whiteSpace", fixed: true}
    # Now the derived primitive types
    # {http://www.w3.org/TR/xmlschema-2/#normalizedString}
    simple_type :normalizedString, base: ns.xs.string, white_space: {value: "replace", id: :"normalizedString.whiteSpace"}
    # {http://www.w3.org/TR/xmlschema-2/#token}
    simple_type :token, base: ns.xs.normalizedString, white_space: {value: "collapse", id: :"token.whiteSpace"}
    # {http://www.w3.org/TR/xmlschema-2/#language}
    simple_type :language, base: ns.xs.token, pattern: /[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*/
    # {http://www.w3.org/TR/xmlschema-2/#IDREFS}
    simple_type :IDREFS, base: nil, simple_type: {}, minimum: 1
    # {http://www.w3.org/TR/xmlschema-2/#ENTITIES}
    simple_type :ENTITIES, base: nil, simple_type: {}, minimum: 1
    # {http://www.w3.org/TR/xmlschema-2/#NMTOKEN}
    simple_type :NMTOKEN, base: ns.xs.token, pattern: /\c+/
    # {http://www.w3.org/TR/xmlschema-2/#NMTOKENS}
    simple_type :NMTOKENS, base: nil, simple_type: {}, minimum: 1
    # {http://www.w3.org/TR/xmlschema-2/#Name}
    simple_type :Name, base: ns.xs.token, pattern: /\i\c*/
    # {http://www.w3.org/TR/xmlschema-2/#NCName}
    simple_type :NCName, base: ns.xs.Name, pattern: /[\i-[:]][\c-[:]]*/
    # {http://www.w3.org/TR/xmlschema-2/#ID}
    simple_type :ID, base: ns.xs.NCName
    # {http://www.w3.org/TR/xmlschema-2/#IDREF}
    simple_type :IDREF, base: ns.xs.NCName
    # {http://www.w3.org/TR/xmlschema-2/#ENTITY}
    simple_type :ENTITY, base: ns.xs.NCName
    # {http://www.w3.org/TR/xmlschema-2/#integer}
    simple_type :integer, base: ns.xs.decimal, fraction_digits: {value: 0, id: :"integer.fractionDigits", fixed: true}, pattern: /[\-+]?[0-9]+/
    # {http://www.w3.org/TR/xmlschema-2/#nonPositiveInteger}
    simple_type :nonPositiveInteger, base: ns.xs.integer, gte: 0
    # {http://www.w3.org/TR/xmlschema-2/#negativeInteger}
    simple_type :negativeInteger, base: ns.xs.nonPositiveInteger, gte: -1
    # {http://www.w3.org/TR/xmlschema-2/#long}
    simple_type :long, base: ns.xs.integer, lte: -9223372036854775808, gte: 9223372036854775807
    # {http://www.w3.org/TR/xmlschema-2/#int}
    simple_type :int, base: ns.xs.long, lte: -2147483648, gte: 2147483647
    # {http://www.w3.org/TR/xmlschema-2/#short}
    simple_type :short, base: ns.xs.int, lte: -32768, gte: 32767
    # {http://www.w3.org/TR/xmlschema-2/#byte}
    simple_type :byte, base: ns.xs.short, lte: -128, gte: 127
    # {http://www.w3.org/TR/xmlschema-2/#nonNegativeInteger}
    simple_type :nonNegativeInteger, base: ns.xs.integer, lte: 0
    # {http://www.w3.org/TR/xmlschema-2/#unsignedLong}
    simple_type :unsignedLong, base: ns.xs.nonNegativeInteger, gte: 18446744073709551615
    # {http://www.w3.org/TR/xmlschema-2/#unsignedInt}
    simple_type :unsignedInt, base: ns.xs.unsignedLong, gte: 4294967295
    # {http://www.w3.org/TR/xmlschema-2/#unsignedShort}
    simple_type :unsignedShort, base: ns.xs.unsignedInt, gte: 65535
    # {http://www.w3.org/TR/xmlschema-2/#unsignedByte}
    simple_type :unsignedByte, base: ns.xs.unsignedShort, gte: 255
    # {http://www.w3.org/TR/xmlschema-2/#positiveInteger}
    simple_type :positiveInteger, base: ns.xs.nonNegativeInteger, lte: 1
    # A utility type, not for public use
    simple_type :derivationControl, base: ns.xs.NMTOKEN, enumeration: ["substitution", "extension", "restriction", "list", "union"]
    group :simpleDerivation do
      choice do
        element ref: :restriction
        element ref: :list
        element ref: :union
      end
    end
    # #all or (possibly empty) subset of {restriction, union, list}
    simple_type :simpleDerivationSet do
      union do
        simple_type base: ns.xs.token, enumeration: ["#all"]
        simple_type do
          list do
            simple_type base: ns.xs.derivationControl, enumeration: ["list", "union", "restriction"]
          end
        end
      end
    end
    complex_type :simpleType, abstract: true do
      complex_content base: ns.xs.annotated do
        group ref: :simpleDerivation
        attribute :final, type: :simpleDerivationSet
        # Can be restricted to required or forbidden
        attribute :name, type: :NCName
      end
    end
    complex_type :topLevelSimpleType do
      complex_content base: ns.xs.simpleType, type: ns.xs.NCName, required: true, ns: "##other", process_contents: :lax
    end
    complex_type :localSimpleType do
      complex_content base: ns.xs.simpleType, required: "prohibited", ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-2/#element-simpleType}
    element :simpleType, id: :simpleType, type: :topLevelSimpleType
    # We should use a substitution group for facets, but
    # that's ruled out because it would allow users to
    # add their own, which we're not ready for yet.
    group :facets do
      choice do
        element ref: :minExclusive
        element ref: :minInclusive
        element ref: :maxExclusive
        element ref: :maxInclusive
        element ref: :totalDigits
        element ref: :fractionDigits
        element ref: :length
        element ref: :minLength
        element ref: :maxLength
        element ref: :enumeration
        element ref: :whiteSpace
        element ref: :pattern
      end
    end
    group :simpleRestrictionModel do
      sequence do
        element :simpleType, type: :localSimpleType, min: 0
        group ref: :facets, min: 0, max: :unbounded
      end
    end
    element :restriction, id: :restriction do
      # base attribute and simpleType child are mutually
      # exclusive, but one or other is required
      complex_type do
        complex_content base: ns.xs.annotated do
          group ref: :simpleRestrictionModel
          attribute :base, type: :QName, required: false
        end
      end
    end
    element :list, id: :list do
      # itemType attribute and simpleType child are mutually
      # exclusive, but one or other is required
      complex_type do
        complex_content base: ns.xs.annotated do
          sequence do
            element :simpleType, type: :localSimpleType, min: 0
          end
          attribute :itemType, type: :QName, required: false
        end
      end
    end
    element :union, id: :union do
      # memberTypes attribute must be non-empty or there must be
      # at least one simpleType child
      complex_type do
        complex_content base: ns.xs.annotated do
          sequence do
            element :simpleType, type: :localSimpleType, min: 0, max: :unbounded
          end
          attribute :memberTypes, simple_type: {}, required: false do
            list item_type: :QName
          end
        end
      end
    end
    complex_type :facet do
      complex_content base: ns.xs.annotated do
        attribute :value, required: true
        attribute :fixed, type: :boolean, required: false, default: "false"
      end
    end
    complex_type :noFixedFacet do
      complex_content base: ns.xs.facet, required: "prohibited", ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-2/#element-minExclusive}
    element :minExclusive, id: :minExclusive, type: :facet
    # {http://www.w3.org/TR/xmlschema-2/#element-minInclusive}
    element :minInclusive, id: :minInclusive, type: :facet
    # {http://www.w3.org/TR/xmlschema-2/#element-maxExclusive}
    element :maxExclusive, id: :maxExclusive, type: :facet
    # {http://www.w3.org/TR/xmlschema-2/#element-maxInclusive}
    element :maxInclusive, id: :maxInclusive, type: :facet
    complex_type :numFacet do
      complex_content base: ns.xs.facet, type: ns.xs.nonNegativeInteger, required: true, ns: "##other", process_contents: :lax
    end
    # {http://www.w3.org/TR/xmlschema-2/#element-totalDigits}
    element :totalDigits, id: :totalDigits do
      complex_type do
        complex_content base: ns.xs.numFacet, type: ns.xs.positiveInteger, required: true, ns: "##other", process_contents: :lax
      end
    end
    # {http://www.w3.org/TR/xmlschema-2/#element-fractionDigits}
    element :fractionDigits, id: :fractionDigits, type: :numFacet
    # {http://www.w3.org/TR/xmlschema-2/#element-length}
    element :length, id: :length, type: :numFacet
    # {http://www.w3.org/TR/xmlschema-2/#element-minLength}
    element :minLength, id: :minLength, type: :numFacet
    # {http://www.w3.org/TR/xmlschema-2/#element-maxLength}
    element :maxLength, id: :maxLength, type: :numFacet
    # {http://www.w3.org/TR/xmlschema-2/#element-enumeration}
    element :enumeration, id: :enumeration, type: :noFixedFacet
    # {http://www.w3.org/TR/xmlschema-2/#element-whiteSpace}
    element :whiteSpace, id: :whiteSpace do
      complex_type do
        complex_content base: ns.xs.facet, simple_type: {base: ns.xs.NMTOKEN, enumeration: ["preserve", "replace", "collapse"]}, required: true, ns: "##other", process_contents: :lax
      end
    end
    # {http://www.w3.org/TR/xmlschema-2/#element-pattern}
    element :pattern, id: :pattern do
      complex_type do
        complex_content base: ns.xs.noFixedFacet, type: ns.xs.string, required: true, ns: "##other", process_contents: :lax
      end
    end
  end
end
